export interface Transaction {
  id?: string; // Optional as it is auto-generated by SQLite
  description: string;
  amount: number;
  type: 'income' | 'expense';
  category: string;
  date: string; // Stored natively as YYYY-MM-DD
  createdAt?: string;
  updatedAt?: string;
}

export interface ApiResponse<T> {
  success: boolean;
  count?: number;
  data: T;
  error?: string;
}